# Generated by Django 5.0.1 on 2026-06-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auth_user_email_unique_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusage',
            name='upload_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
