# Generated by Django 6.0.5 on 2026-06-01 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userusage_upload_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userusage',
            name='concurrent_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userusage',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userusage',
            name='last_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userusage',
            index=models.Index(fields=['device_fingerprint', 'date'], name='accounts_us_device__ae200d_idx'),
        ),
        migrations.AddIndex(
            model_name='userusage',
            index=models.Index(fields=['user', 'concurrent_requests'], name='accounts_us_user_id_10a838_idx'),
        ),
    ]
