# Generated by Django 5.0.1 on 2026-06-06 11:59

import django.core.validators
import django.db.models.deletion
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgvector.django.CreateExtension('vector'),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('text_content', models.TextField()),
                ('token_count', models.IntegerField()),
                ('embedding', pgvector.django.VectorField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.source')),
            ],
            options={
                'ordering': ['source', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['workspace', 'status'], name='sources_sou_workspa_407f58_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['user', 'created_at'], name='sources_sou_user_id_9a80ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('workspace', 'original_filename')},
        ),
        migrations.AddIndex(
            model_name='sourcechunk',
            index=models.Index(fields=['source', 'chunk_index'], name='sources_sou_source__9ae51e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcechunk',
            unique_together={('source', 'chunk_index')},
        ),
    ]
