# Generated by Django 6.0.5 on 2026-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
