"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _get_allowed_hosts() -> list[str]:
    raw_hosts = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
    return [host.strip() for host in raw_hosts.split(',') if host.strip()]


def _get_database_config() -> dict[str, dict[str, str | Path | int]]:
    database_url = os.getenv('DATABASE_URL', '').strip()
    if not database_url:
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

    parsed_url = urlparse(database_url)
    if parsed_url.scheme in ('postgres', 'postgresql'):
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': parsed_url.path.lstrip('/'),
                'USER': parsed_url.username or '',
                'PASSWORD': parsed_url.password or '',
                'HOST': parsed_url.hostname or '',
                'PORT': parsed_url.port or '',
            }
        }

    if parsed_url.scheme == 'sqlite':
        database_name = parsed_url.path or database_url.removeprefix('sqlite://')
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': database_name,
            }
        }

    raise ValueError(f"Skema DATABASE_URL tidak didukung: {parsed_url.scheme}")


def _env_bool(name: str, default: str = 'false') -> bool:
    return os.getenv(name, default).strip().lower() in ('1', 'true', 'yes')


def _get_email_mode() -> str:
    mode = os.getenv('EMAIL_MODE', '').strip().lower()
    if mode in ('dev', 'development'):
        return 'console'
    if not mode:
        return 'smtp' if os.getenv('EMAIL_BACKEND') else 'console'
    return mode


def _get_email_config() -> dict[str, str | int | bool]:
    mode = _get_email_mode()

    default_from_email = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@mythosnote.local')

    if mode == 'console':
        return {
            'EMAIL_BACKEND': 'django.core.mail.backends.console.EmailBackend',
            'DEFAULT_FROM_EMAIL': default_from_email,
        }

    if mode == 'brevo':
        brevo_host = os.getenv('BREVO_SMTP_HOST', 'smtp-relay.brevo.com')
        brevo_user = os.getenv('BREVO_SMTP_USER', '')
        if brevo_user == brevo_host:
            raise ValueError("BREVO_SMTP_USER harus SMTP login Brevo, bukan host SMTP.")

        return {
            'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'EMAIL_HOST': brevo_host,
            'EMAIL_PORT': int(os.getenv('BREVO_SMTP_PORT', '587')),
            'EMAIL_USE_TLS': _env_bool('BREVO_SMTP_USE_TLS', 'true'),
            'EMAIL_HOST_USER': brevo_user,
            'EMAIL_HOST_PASSWORD': os.getenv('BREVO_SMTP_KEY', ''),
            'DEFAULT_FROM_EMAIL': default_from_email,
        }

    if mode == 'smtp':
        return {
            'EMAIL_BACKEND': os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'),
            'EMAIL_HOST': os.getenv('EMAIL_HOST', ''),
            'EMAIL_PORT': int(os.getenv('EMAIL_PORT', '587')),
            'EMAIL_USE_TLS': _env_bool('EMAIL_USE_TLS', 'true'),
            'EMAIL_USE_SSL': _env_bool('EMAIL_USE_SSL'),
            'EMAIL_HOST_USER': os.getenv('EMAIL_HOST_USER', ''),
            'EMAIL_HOST_PASSWORD': os.getenv('EMAIL_HOST_PASSWORD', ''),
            'DEFAULT_FROM_EMAIL': default_from_email,
        }

    raise ValueError("EMAIL_MODE harus salah satu: console, development, smtp, brevo")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY tidak ditemukan di environment variables!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').strip().lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = _get_allowed_hosts()

FRONTEND_URL = os.getenv("FRONTEND_URL", "").strip()
CSRF_TRUSTED_ORIGINS = [FRONTEND_URL] if FRONTEND_URL else []

AUTHENTICATION_BACKENDS = [
    "apps.accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Application definition

INSTALLED_APPS = [
    'apps.accounts.apps.AccountsConfig',
    'apps.sources.apps.SourcesConfig',
    'apps.workspaces.apps.WorkspacesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_rq',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.accounts.context_processors.auth_settings',
                'apps.accounts.context_processors.navbar_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = _get_database_config()

# RQ (Redis Queue) Configuration
# https://django-rq.readthedocs.io/en/latest/configuration.html
REDIS_URL = os.getenv('REDIS_URL', '').strip()
if REDIS_URL:
    RQ_QUEUES = {
        'default': {
            'URL': REDIS_URL,
            'DEFAULT_TIMEOUT': 360,
        },
    }
else:
    RQ_QUEUES = {
        'default': {
            'HOST': 'localhost',
            'PORT': 6379,
            'DB': 0,
            'DEFAULT_TIMEOUT': 360,
        },
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session-based auth defaults. Workspace/core feature views can use
# apps.accounts.decorators.verified_email_required when those apps are added.
LOGIN_URL = 'signin'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# EMAIL_MODE keeps switching simple:
# console/development prints email locally, smtp uses generic SMTP, brevo uses Brevo SMTP relay.
EMAIL_MODE = _get_email_mode()
globals().update(_get_email_config())
EMAIL_ASYNC = _env_bool('EMAIL_ASYNC')
UNVERIFIED_USER_CLEANUP_DAYS = int(os.getenv('UNVERIFIED_USER_CLEANUP_DAYS', '1'))

# Public Google Identity Services client id. When empty, the template keeps
# the Google button disabled without breaking email/password auth.
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '').strip()
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '').strip()
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '').strip()
DEEPSEEK_BASE_URL = os.getenv('DEEPSEEK_BASE_URL', 'https://api.deepseek.com/v1').strip()

# AI Provider options and validation
AI_PROVIDER = os.getenv('AI_PROVIDER', 'gemini').strip().lower()
if AI_PROVIDER not in ('gemini', 'openai', 'deepseek'):
    raise ValueError(f"Unsupported AI_PROVIDER: {AI_PROVIDER!r}. Use 'gemini', 'openai', or 'deepseek'.")

EMBEDDING_PROVIDER = os.getenv('EMBEDDING_PROVIDER', 'openai').strip().lower()
# Security settings for modern browsers to mitigate certain types of attacks. Adjust as needed.
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# Production cookie/transport defaults stay strict, while DEBUG keeps local
# HTTP development usable unless explicitly overridden.
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', 'false' if DEBUG else 'true')
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', 'false' if DEBUG else 'true')
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', 'false' if DEBUG else 'true')
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'false' if DEBUG else 'true')
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', 'false' if DEBUG else 'true')
